# Generated by Django 4.1.4 on 2022-12-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='question_list',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
