# Generated by Django 4.1.4 on 2023-01-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_result_current_question_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
