# Generated by Django 4.1.4 on 2023-02-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_result_examresultdetail_examresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examresultdetail",
            name="examresult",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.examresult"
            ),
        ),
    ]
